### ISSUE TITLE
Cannot find video track

### ISSUE THREAD

**Issue by SchnMar** [AbedElazizShe/light_compressor#6]
Hello,

first of all thank you for this easy to use, great package. Unfortunately, there is an error saying cannot find video track for quiet a lot of videos on my iPhone. What could be the reason for this? Is there a way to get additional information about this?

Thank you
Marcel

**Comment by AbedElazizShe** [comment]
@SchnMar Thank you for opening this issue and i am sorry you're facing it. I think it has to do with missing metadata of the videos. The plugin used to pick the videos could play a major role in this. Could you please try the sample apk in README? Let me know if it is happening. You could as will provide a sample video and information on which plugin you're using, Android/iOS versions and the device. Thank you.

**Comment by hungvinh1234** [comment]
I have same error, did you guys find any solution ?

**Comment by hungvinh1234** [comment]
In my case that error caused by missing meta data of picked video.
I picked video file from AssetEntity.file and it not contain the meta data of video file.
When i change AssetEntity.file =>  AssetEntity.originFile to make it contain EXIF information, the error is solved.
So that, make sure your picked video contain meta data of video.

**Comment by AbedElazizShe** [comment]
@hungvinh1234 Thank you for confirming this. @SchnMar Does that solve your issue ?

**Comment by SchnMar** [comment]
Hello, works like a charm. Sorry for the late reply. 

Thank you!

**Comment by Mudassar-Afzal-Ch** [comment]
@hungvinh1234 @SchnMar @AbedElazizShe  how to change AssetEntity.file => AssetEntity.originFile ?
